# Generated by Django 4.1.1 on 2023-10-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("season_05", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="stat",
            field=models.CharField(
                choices=[
                    ("MatchesCompleted", "MatchesCompleted"),
                    ("Wins", "Wins"),
                    ("Losses", "Losses"),
                    ("Ties", "Ties"),
                    ("CoreStats_Score", "Score"),
                    ("CoreStats_PersonalScore", "PersonalScore"),
                    ("CoreStats_RoundsWon", "RoundsWon"),
                    ("CoreStats_RoundsLost", "RoundsLost"),
                    ("CoreStats_RoundsTied", "RoundsTied"),
                    ("CoreStats_Kills", "Kills"),
                    ("CoreStats_Deaths", "Deaths"),
                    ("CoreStats_Assists", "Assists"),
                    ("CoreStats_Suicides", "Suicides"),
                    ("CoreStats_Betrayals", "Betrayals"),
                    ("CoreStats_GrenadeKills", "GrenadeKills"),
                    ("CoreStats_HeadshotKills", "HeadshotKills"),
                    ("CoreStats_MeleeKills", "MeleeKills"),
                    ("CoreStats_PowerWeaponKills", "PowerWeaponKills"),
                    ("CoreStats_ShotsFired", "ShotsFired"),
                    ("CoreStats_ShotsHit", "ShotsHit"),
                    ("CoreStats_DamageDealt", "DamageDealt"),
                    ("CoreStats_DamageTaken", "DamageTaken"),
                    ("CoreStats_CalloutAssists", "CalloutAssists"),
                    ("CoreStats_VehicleDestroys", "VehicleDestroys"),
                    ("CoreStats_DriverAssists", "DriverAssists"),
                    ("CoreStats_Hijacks", "Hijacks"),
                    ("CoreStats_EmpAssists", "EmpAssists"),
                    ("CoreStats_MaxKillingSpree", "MaxKillingSpree"),
                    ("CoreStats_Medals", "Medal Count"),
                    (
                        "CaptureTheFlagStats_FlagCaptureAssists",
                        "CTF: FlagCaptureAssists",
                    ),
                    ("CaptureTheFlagStats_FlagCaptures", "CTF: FlagCaptures"),
                    (
                        "CaptureTheFlagStats_FlagCarriersKilled",
                        "CTF: FlagCarriersKilled",
                    ),
                    ("CaptureTheFlagStats_FlagGrabs", "CTF: FlagGrabs"),
                    (
                        "CaptureTheFlagStats_FlagReturnersKilled",
                        "CTF: FlagReturnersKilled",
                    ),
                    ("CaptureTheFlagStats_FlagReturns", "CTF: FlagReturns"),
                    ("CaptureTheFlagStats_FlagSecures", "CTF: FlagSecures"),
                    ("CaptureTheFlagStats_FlagSteals", "CTF: FlagSteals"),
                    (
                        "CaptureTheFlagStats_KillsAsFlagCarrier",
                        "CTF: KillsAsFlagCarrier",
                    ),
                    (
                        "CaptureTheFlagStats_KillsAsFlagReturner",
                        "CTF: KillsAsFlagReturner",
                    ),
                    ("EliminationStats_AlliesRevived", "Elimination: AlliesRevived"),
                    (
                        "EliminationStats_EliminationAssists",
                        "Elimination: EliminationAssists",
                    ),
                    ("EliminationStats_Eliminations", "Elimination: Eliminations"),
                    (
                        "EliminationStats_EnemyRevivesDenied",
                        "Elimination: EnemyRevivesDenied",
                    ),
                    ("EliminationStats_Executions", "Elimination: Executions"),
                    (
                        "EliminationStats_KillsAsLastPlayerStanding",
                        "Elimination: KillsAsLastPlayerStanding",
                    ),
                    (
                        "EliminationStats_LastPlayersStandingKilled",
                        "Elimination: LastPlayersStandingKilled",
                    ),
                    ("EliminationStats_RoundsSurvived", "Elimination: RoundsSurvived"),
                    (
                        "EliminationStats_TimesRevivedByAlly",
                        "Elimination: TimesRevivedByAlly",
                    ),
                    ("InfectionStats_AlphasKilled", "Infection: AlphasKilled"),
                    ("InfectionStats_SpartansInfected", "Infection: SpartansInfected"),
                    (
                        "InfectionStats_SpartansInfectedAsAlpha",
                        "Infection: SpartansInfectedAsAlpha",
                    ),
                    (
                        "InfectionStats_KillsAsLastSpartanStanding",
                        "Infection: KillsAsLastSpartanStanding",
                    ),
                    (
                        "InfectionStats_LastSpartansStandingInfected",
                        "Infection: LastSpartansStandingInfected",
                    ),
                    ("InfectionStats_RoundsAsAlpha", "Infection: RoundsAsAlpha"),
                    (
                        "InfectionStats_RoundsAsLastSpartanStanding",
                        "Infection: RoundsAsLastSpartanStanding",
                    ),
                    (
                        "InfectionStats_RoundsFinishedAsInfected",
                        "Infection: RoundsFinishedAsInfected",
                    ),
                    (
                        "InfectionStats_RoundsSurvivedAsSpartan",
                        "Infection: RoundsSurvivedAsSpartan",
                    ),
                    (
                        "InfectionStats_RoundsSurvivedAsLastSpartanStanding",
                        "Infection: RoundsSurvivedAsLastSpartanStanding",
                    ),
                    ("InfectionStats_InfectedKilled", "Infection: InfectedKilled"),
                    (
                        "OddballStats_KillsAsSkullCarrier",
                        "Oddball: KillsAsSkullCarrier",
                    ),
                    (
                        "OddballStats_SkullCarriersKilled",
                        "Oddball: SkullCarriersKilled",
                    ),
                    ("OddballStats_SkullGrabs", "Oddball: SkullGrabs"),
                    ("OddballStats_SkullScoringTicks", "Oddball: SkullScoringTicks"),
                    ("ZonesStats_ZoneCaptures", "Zones: ZoneCaptures"),
                    ("ZonesStats_ZoneDefensiveKills", "Zones: ZoneDefensiveKills"),
                    ("ZonesStats_ZoneOffensiveKills", "Zones: ZoneOffensiveKills"),
                    ("ZonesStats_ZoneSecures", "Zones: ZoneSecures"),
                    ("ZonesStats_ZoneScoringTicks", "Zones: ZoneScoringTicks"),
                    (
                        "StockpileStats_KillsAsPowerSeedCarrier",
                        "Stockpile: KillsAsPowerSeedCarrier",
                    ),
                    (
                        "StockpileStats_PowerSeedCarriersKilled",
                        "Stockpile: PowerSeedCarriersKilled",
                    ),
                    (
                        "StockpileStats_PowerSeedsDeposited",
                        "Stockpile: PowerSeedsDeposited",
                    ),
                    ("StockpileStats_PowerSeedsStolen", "Stockpile: PowerSeedsStolen"),
                ],
                max_length=128,
                verbose_name="Stat",
            ),
        ),
    ]
