# Generated by Django 4.1.1 on 2023-10-20 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("season_05", "0006_alter_domain_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={
                "ordering": ["effective_date", "created_at"],
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
            },
        ),
    ]
