# Generated by Django 4.1.1 on 2022-10-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("series", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seriesruleset",
            name="id",
            field=models.CharField(
                max_length=32, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
