# Generated by Django 4.1.1 on 2022-12-15 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("xbox_live", "0003_remove_xboxliveaccount_id_xboxliveaccount_xuid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discord", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordXboxLiveLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Verified?"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discord_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="discord.discordaccount",
                        verbose_name="Discord Account",
                    ),
                ),
                (
                    "xbox_live_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="xbox_live.xboxliveaccount",
                        verbose_name="Xbox Live Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord/Xbox Live Link",
                "verbose_name_plural": "Discord/Xbox Live Links",
                "db_table": "DiscordXboxLiveLink",
                "ordering": ["-updated_at"],
            },
        ),
    ]
