# Generated by Django 4.1.1 on 2023-02-22 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("link", "0002_alter_discordxboxlivelink_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordxboxlivelink",
            name="verifier",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="verifiers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
