# Generated by Django 4.1.1 on 2022-10-12 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternChatterPause",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discord_user_id",
                    models.CharField(max_length=32, verbose_name="Discord User ID"),
                ),
                (
                    "discord_user_tag",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Discord Username"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pause",
                "verbose_name_plural": "Pauses",
                "db_table": "InternChatterPause",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InternChatterForbiddenChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discord_channel_id",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Discord Channel ID"
                    ),
                ),
                (
                    "discord_channel_name",
                    models.TextField(blank=True, verbose_name="Discord Channel Name"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Forbidden Channel",
                "verbose_name_plural": "Forbidden Channels",
                "db_table": "InternChatterForbiddenChannel",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="InternChatter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_text",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Message Text"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chatter",
                "verbose_name_plural": "Chatters",
                "db_table": "InternChatter",
                "ordering": ["-updated_at"],
            },
        ),
    ]
