# Generated by Django 4.1.1 on 2023-01-08 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("intern", "0002_alter_internchatterforbiddenchannel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternHelpfulHint",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_text",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Message Text"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Helpful Hint",
                "verbose_name_plural": "Helpful Hints",
                "db_table": "InternHelpfulHint",
                "ordering": ["-updated_at"],
            },
        ),
    ]
