# Generated by Django 4.1.1 on 2023-06-06 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discord", "0003_alter_discordaccount_discord_username"),
        ("intern", "0004_internplusrepquip_internnewhereyeetquip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internchatterpause",
            name="pauser",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pausers",
                to="discord.discordaccount",
            ),
        ),
    ]
