# Generated by Django 4.1.1 on 2023-06-07 05:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intern", "0005_internchatterpause_pauser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internchatterpause",
            name="discord_user_id",
        ),
        migrations.RemoveField(
            model_name="internchatterpause",
            name="discord_user_tag",
        ),
    ]
