# Generated by Django 4.1.1 on 2023-09-10 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("intern", "0006_remove_internchatterpause_discord_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternPassionReportQuip",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quip_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Quip Text"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Passion Report Quip",
                "verbose_name_plural": "Passion Report Quips",
                "db_table": "InternPassionReportQuip",
                "ordering": ["-updated_at"],
            },
        ),
    ]
