app = "hftbackend"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "sh /app/scripts/release.sh"

[env]
  DATABASE_URL = "$DATABASE_URL"
  DEBUG = "False"
  ENVIRONMENT = "prod"
  PRIMARY_REGION = "dfw"
  SECRET_KEY = "$SECRET_KEY"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[restart]]
  policy = "always"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  # [[services.http_checks]]
  #   interval = 15000
  #   grace_period = "5s"
  #   method = "get"
  #   path = "/ping"
  #   protocol = "https"
  #   timeout = 2000
  #   tls_skip_verify = true

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
