# Generated by Django 5.0.1 on 2024-01-13 02:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("discord", "0004_discordlfgthreadhelpprompt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BingoBuff",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_at", models.DateTimeField()),
                ("bingo_count", models.IntegerField(default=0)),
                ("challenge_count", models.IntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "earner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bingo_buff",
                        to="discord.discordaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bingo Buff",
                "verbose_name_plural": "Bingo Buffs",
                "db_table": "BingoBuff",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BingoChallengeParticipant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "board_order",
                    models.CharField(
                        max_length=25,
                        validators=[django.core.validators.MinLengthValidator(25)],
                        verbose_name="Board Order",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bingo_participants",
                        to="discord.discordaccount",
                        verbose_name="Participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "db_table": "BingoChallengeParticipant",
                "ordering": ["-created_at"],
            },
        ),
    ]
