# Generated by Django 5.0.1 on 2024-01-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("season_06", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bingochallengeparticipant",
            name="most_recent_match_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Most Recent Match ID"
            ),
        ),
    ]
