# Generated by Django 5.0.1 on 2024-01-15 06:27

import apps.season_06.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("halo_infinite", "0004_haloinfinitematch"),
        ("season_06", "0002_bingochallengeparticipant_most_recent_match_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BingoChallenge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "description",
                    models.CharField(max_length=256, verbose_name="Description"),
                ),
                (
                    "require_match_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Custom"), (3, "Matchmade")],
                        null=True,
                        verbose_name="Match Type",
                    ),
                ),
                (
                    "require_level_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Level Canvas ID"
                    ),
                ),
                (
                    "require_map_asset_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Map File ID"),
                ),
                (
                    "require_mode_asset_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Mode File ID"
                    ),
                ),
                (
                    "require_playlist_asset_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Playlist ID"),
                ),
                (
                    "require_present_at_beginning",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Present at Game Start"
                    ),
                ),
                (
                    "require_present_at_completion",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Present at Game End"
                    ),
                ),
                (
                    "stat",
                    models.CharField(
                        choices=apps.season_06.models.get_stat_choices,
                        max_length=128,
                        verbose_name="Stat",
                    ),
                ),
                (
                    "medal_id",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Medal ID (only necessary if Stat is 'Medals')",
                    ),
                ),
                ("score", models.CharField(max_length=128, verbose_name="Score")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge",
                "verbose_name_plural": "Challenges",
                "db_table": "BingoChallenge",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="BingoChallengeCompletion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="completions",
                        to="season_06.bingochallenge",
                        verbose_name="Completion",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="completions",
                        to="halo_infinite.haloinfinitematch",
                        verbose_name="Completion",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="completions",
                        to="season_06.bingochallengeparticipant",
                        verbose_name="Completion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge Completion",
                "verbose_name_plural": "Challenge Completions",
                "db_table": "BingoChallengeCompletion",
                "ordering": ["-created_at"],
            },
        ),
    ]
