# Generated by Django 4.1.1 on 2023-06-15 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("season_04", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StampChallengeBTBMatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.CharField(
                        choices=[
                            ("16", "Finish in Five"),
                            ("17", "Victory Lap"),
                            ("18", "Type A"),
                            ("19", "Formerly Chuck's"),
                            ("20", "In Particular"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "match_id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="Match ID"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stamp Challenge BTB Match",
                "verbose_name_plural": "Stamp Challenge BTB Matches",
                "db_table": "StampChallengeBTBMatch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StampChallenge20Completion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xuid", models.PositiveBigIntegerField(verbose_name="Xbox Live ID")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="season_04.stampchallengebtbmatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stamp Challenge Completion: In Particular",
                "verbose_name_plural": "Stamp Challenge Completions: In Particular",
                "db_table": "StampChallenge20Completion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StampChallenge19Completion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xuid", models.PositiveBigIntegerField(verbose_name="Xbox Live ID")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="season_04.stampchallengebtbmatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stamp Challenge Completion: Formerly Chuck's",
                "verbose_name_plural": "Stamp Challenge Completions: Formerly Chuck's",
                "db_table": "StampChallenge19Completion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StampChallenge18Completion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xuid", models.PositiveBigIntegerField(verbose_name="Xbox Live ID")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="season_04.stampchallengebtbmatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stamp Challenge Completion: Type A",
                "verbose_name_plural": "Stamp Challenge Completions: Type A",
                "db_table": "StampChallenge18Completion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StampChallenge17Completion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xuid", models.PositiveBigIntegerField(verbose_name="Xbox Live ID")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="season_04.stampchallengebtbmatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stamp Challenge Completion: Victory Lap",
                "verbose_name_plural": "Stamp Challenge Completions: Victory Lap",
                "db_table": "StampChallenge17Completion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StampChallenge16Completion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xuid", models.PositiveBigIntegerField(verbose_name="Xbox Live ID")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="season_04.stampchallengebtbmatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stamp Challenge Completion: Finish in Five",
                "verbose_name_plural": "Stamp Challenge Completions: Finish in Five",
                "db_table": "StampChallenge16Completion",
                "ordering": ["-created_at"],
            },
        ),
    ]
