# Generated by Django 4.1.1 on 2023-06-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "season_04",
            "0002_stampchallengebtbmatch_stampchallenge20completion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stampchampearner",
            name="stamp_count",
            field=models.IntegerField(default=0),
        ),
    ]
