# Generated by Django 4.1.1 on 2023-02-27 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("halo_infinite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HaloInfiniteSeason",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "season_id",
                    models.CharField(
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Season ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Season Name")),
                ("start_date", models.DateTimeField(verbose_name="Start Date & Time")),
                ("end_date", models.DateTimeField(verbose_name="End Date & Time")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "db_table": "HaloInfiniteSeason",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="HaloInfinitePlaylist",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "playlist_id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="Playlist ID"
                    ),
                ),
                ("version_id", models.UUIDField(blank=True, verbose_name="Version ID")),
                ("ranked", models.BooleanField()),
                ("active", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, max_length=256)),
                ("description", models.TextField(blank=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
                "db_table": "HaloInfinitePlaylist",
                "ordering": ["created_at"],
            },
        ),
    ]
