# Generated by Django 5.0.1 on 2024-01-25 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("halo_infinite", "0004_haloinfinitematch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="haloinfiniteplaylist",
            options={
                "ordering": ["-active", "name"],
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
            },
        ),
        migrations.DeleteModel(
            name="HaloInfiniteSeason",
        ),
    ]
