# Generated by Django 5.0.6 on 2024-06-05 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("halo_infinite", "0005_alter_haloinfiniteplaylist_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HaloInfiniteMap",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="Asset ID"
                    ),
                ),
                ("version_id", models.UUIDField(blank=True, verbose_name="Version ID")),
                (
                    "public_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Map Name"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Map Description"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, verbose_name="Published Time"),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Raw Data"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Map",
                "verbose_name_plural": "Maps",
                "db_table": "HaloInfiniteMap",
                "ordering": ["-published_at"],
            },
        ),
    ]
