# Generated by Django 5.0.6 on 2024-06-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("halo_infinite", "0007_alter_haloinfinitebuildid_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="haloinfiniteplaylist",
            name="data",
            field=models.JSONField(blank=True, default=dict, verbose_name="Raw Data"),
        ),
        migrations.AddField(
            model_name="haloinfiniteplaylist",
            name="info",
            field=models.JSONField(blank=True, default=dict, verbose_name="Raw Info"),
        ),
    ]
