# Generated by Django 5.0.6 on 2024-06-07 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("halo_infinite", "0008_haloinfiniteplaylist_data_haloinfiniteplaylist_info"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="haloinfinitemap",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="haloinfinitemap",
            name="public_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Name"),
        ),
        migrations.CreateModel(
            name="HaloInfiniteMapModePair",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "asset_id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="Asset ID"
                    ),
                ),
                ("version_id", models.UUIDField(blank=True, verbose_name="Version ID")),
                (
                    "public_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Name"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Raw Data"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MapModePair",
                "verbose_name_plural": "MapModePairs",
                "db_table": "HaloInfiniteMapModePair",
                "ordering": ["-updated_at"],
            },
        ),
    ]
