# Generated by Django 4.1.1 on 2023-06-06 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discord", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discordaccount",
            options={
                "ordering": ["discord_username"],
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.RenameField(
            model_name="discordaccount",
            old_name="discord_tag",
            new_name="discord_username",
        ),
    ]
