# Generated by Django 4.1.1 on 2024-01-01 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discord", "0003_alter_discordaccount_discord_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordLFGThreadHelpPrompt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lfg_thread_name",
                    models.CharField(max_length=100, verbose_name="LFG Thread Name"),
                ),
                (
                    "lfg_thread_id",
                    models.CharField(max_length=20, verbose_name="LFG Thread ID"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "help_receiver_discord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="lfg_thread_help_receivers",
                        to="discord.discordaccount",
                        verbose_name="Help Receiver Discord",
                    ),
                ),
            ],
            options={
                "verbose_name": "LFG Thread Help Prompt",
                "verbose_name_plural": "LFG Thread Help Prompts",
                "db_table": "DiscordLFGThreadHelpPrompt",
                "ordering": ["-created_at"],
            },
        ),
    ]
