# Generated by Django 4.1.1 on 2023-06-07 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discord", "0003_alter_discordaccount_discord_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordaccount",
            name="discord_username",
            field=models.CharField(
                max_length=37,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Discord Username",
            ),
        ),
    ]
