# Generated by Django 5.0.1 on 2024-02-01 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discord", "0004_discordlfgthreadhelpprompt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordLFGChannelHelpPrompt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lfg_channel_name",
                    models.CharField(max_length=100, verbose_name="LFG Channel Name"),
                ),
                (
                    "lfg_channel_id",
                    models.CharField(max_length=20, verbose_name="LFG Channel ID"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "help_receiver_discord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="lfg_channel_help_receivers",
                        to="discord.discordaccount",
                        verbose_name="Help Receiver Discord",
                    ),
                ),
            ],
            options={
                "verbose_name": "LFG Channel Help Prompt",
                "verbose_name_plural": "LFG Channel Help Prompts",
                "db_table": "DiscordLFGChannelHelpPrompt",
                "ordering": ["-created_at"],
            },
        ),
    ]
