# Generated by Django 5.1.4 on 2025-03-12 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era_03', '0002_alter_boatrank_track_boatassignment_and_more'),
        ('halo_infinite', '0009_alter_haloinfinitemap_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatSecret',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medal_id', models.IntegerField(verbose_name='Medal ID')),
                ('title', models.TextField(max_length=64, verbose_name='Title')),
                ('hint', models.TextField(max_length=256, verbose_name='Hint')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boat Secret',
                'verbose_name_plural': 'Boat Secrets',
                'db_table': 'BoatSecret',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoatSecretUnlock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deckhand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='secrets_unlocked', to='era_03.boatdeckhand', verbose_name='Deckhand')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='halo_infinite.haloinfinitematch')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='unlocks', to='era_03.boatsecret', verbose_name='Secret')),
            ],
            options={
                'verbose_name': 'Boat Secret Unlock',
                'verbose_name_plural': 'Boat Secret Unlocks',
                'db_table': 'BoatSecretUnlock',
                'ordering': ['-created_at'],
            },
        ),
    ]
