# Generated by Django 5.1.4 on 2025-03-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era_03', '0003_boatsecret_boatsecretunlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatsecret',
            name='medal_id',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Medal ID'),
        ),
    ]
