# Generated by Django 4.1.1 on 2023-03-13 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("discord", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pathfinder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pathfinderhikesubmission",
            name="map_submitter_discord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pathfinder_hike_submitters",
                to="discord.discordaccount",
                verbose_name="Map Submitter Discord",
            ),
        ),
        migrations.CreateModel(
            name="PathfinderWAYWOPost",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "post_title",
                    models.CharField(max_length=100, verbose_name="Post Title"),
                ),
                ("post_id", models.CharField(max_length=20, verbose_name="Post ID")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "poster_discord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pathfinder_waywo_posters",
                        to="discord.discordaccount",
                        verbose_name="Poster Discord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hike Attendance",
                "verbose_name_plural": "Hike Attendances",
                "db_table": "PathfinderWAYWOPost",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PathfinderHikeAttendance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attendance_date", models.DateField(verbose_name="Attendance Date")),
                (
                    "attendee_discord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pathfinder_hike_attendees",
                        to="discord.discordaccount",
                        verbose_name="Attendee Discord",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hike Attendance",
                "verbose_name_plural": "Hike Attendances",
                "db_table": "PathfinderHikeAttendance",
                "ordering": ["-attendance_date"],
            },
        ),
    ]
