# Generated by Django 4.1.1 on 2023-03-13 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "pathfinder",
            "0002_alter_pathfinderhikesubmission_map_submitter_discord_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pathfinderwaywopost",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "WAYWO Post",
                "verbose_name_plural": "WAYWO Posts",
            },
        ),
    ]
