# Generated by Django 4.1.1 on 2023-05-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathfinder", "0003_alter_pathfinderwaywopost_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathfinderhikesubmission",
            name="category",
            field=models.CharField(max_length=32, null=True, verbose_name="Category"),
        ),
        migrations.AlterField(
            model_name="pathfinderhikesubmission",
            name="scheduled_playtest_date",
            field=models.DateField(null=True, verbose_name="Scheduled Playtest Date"),
        ),
    ]
