# Generated by Django 4.1.1 on 2023-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathfinder", "0004_pathfinderhikesubmission_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pathfinderhikesubmission",
            name="category",
        ),
        migrations.AddField(
            model_name="pathfinderhikesubmission",
            name="max_player_count",
            field=models.CharField(
                max_length=32, null=True, verbose_name="Max Player Count"
            ),
        ),
        migrations.AlterField(
            model_name="pathfinderhikesubmission",
            name="scheduled_playtest_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Scheduled Playtest Date"
            ),
        ),
    ]
