# Generated by Django 4.1.1 on 2023-06-19 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discord", "0003_alter_discordaccount_discord_username"),
        ("pathfinder", "0005_remove_pathfinderhikesubmission_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PathfinderTestingLFGPost",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "post_title",
                    models.CharField(max_length=100, verbose_name="Post Title"),
                ),
                ("post_id", models.CharField(max_length=20, verbose_name="Post ID")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "poster_discord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pathfinder_testing_lfg_posters",
                        to="discord.discordaccount",
                        verbose_name="Poster Discord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testing LFG Post",
                "verbose_name_plural": "Testing LFG Posts",
                "db_table": "PathfinderTestingLFGPost",
                "ordering": ["-created_at"],
            },
        ),
    ]
