# Generated by Django 4.1.1 on 2023-10-28 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("discord", "0003_alter_discordaccount_discord_username"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pathfinder", "0006_pathfindertestinglfgpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathfinderhikesubmission",
            name="mode",
            field=models.CharField(
                default="Slayer", max_length=32, verbose_name="Mode"
            ),
        ),
        migrations.AddField(
            model_name="pathfinderhikesubmission",
            name="playtest_game_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Playtest Game ID"
            ),
        ),
        migrations.CreateModel(
            name="PathfinderWAYWOComment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("post_id", models.CharField(max_length=20, verbose_name="Post ID")),
                (
                    "comment_id",
                    models.CharField(max_length=20, verbose_name="Comment ID"),
                ),
                ("comment_length", models.IntegerField(verbose_name="Comment Length")),
                (
                    "commenter_discord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pathfinder_waywo_commenters",
                        to="discord.discordaccount",
                        verbose_name="Commenter Discord",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WAYWO Comment",
                "verbose_name_plural": "WAYWO Comments",
                "db_table": "PathfinderWAYWOComment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PathfinderHikeVoiceParticipation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pathfinder_hike_voice_participants",
                        to="discord.discordaccount",
                    ),
                ),
                (
                    "hike_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pathfinder.pathfinderhikesubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathfinder Hike Voice Participation",
                "verbose_name_plural": "Pathfinder Hike Voice Participations",
                "db_table": "PathfinderHikeVoiceParticipation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PathfinderHikeGameParticipation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xuid", models.PositiveBigIntegerField(verbose_name="Xbox Live ID")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hike_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pathfinder.pathfinderhikesubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathfinder Hike Game Participation",
                "verbose_name_plural": "Pathfinder Hike Game Participations",
                "db_table": "PathfinderHikeGameParticipation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PathfinderBeanCount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("count", models.IntegerField(verbose_name="Count")),
                (
                    "bean_owner_discord",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pathfinder_bean_owners",
                        to="discord.discordaccount",
                        verbose_name="Discord",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bean Count",
                "verbose_name_plural": "Bean Counts",
                "db_table": "PathfinderBeanCount",
                "ordering": ["-count"],
            },
        ),
    ]
