# Generated by Django 4.1.1 on 2023-10-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discord", "0003_alter_discordaccount_discord_username"),
        ("pathfinder", "0007_pathfinderhikesubmission_mode_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pathfinderbeancount",
            options={
                "ordering": ["-bean_count"],
                "verbose_name": "Bean Count",
                "verbose_name_plural": "Bean Counts",
            },
        ),
        migrations.RemoveField(
            model_name="pathfinderbeancount",
            name="count",
        ),
        migrations.AddField(
            model_name="pathfinderbeancount",
            name="bean_count",
            field=models.IntegerField(default=0, verbose_name="Bean Count"),
        ),
        migrations.AlterField(
            model_name="pathfinderbeancount",
            name="bean_owner_discord",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pathfinder_bean_owners",
                to="discord.discordaccount",
                verbose_name="Bean Owner Discord",
            ),
        ),
    ]
