# Generated by Django 5.0.6 on 2024-06-08 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discord", "0006_alter_discordaccount_created_at_and_more"),
        ("pathfinder", "0009_alter_pathfinderbeancount_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pathfindertestinglfgpost",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="pathfindertestinglfgpost",
            name="poster_discord",
        ),
        migrations.RemoveField(
            model_name="pathfinderhikesubmission",
            name="mode_1",
        ),
        migrations.RemoveField(
            model_name="pathfinderhikesubmission",
            name="mode_1_played",
        ),
        migrations.RemoveField(
            model_name="pathfinderhikesubmission",
            name="mode_2",
        ),
        migrations.RemoveField(
            model_name="pathfinderhikesubmission",
            name="mode_2_played",
        ),
        migrations.RemoveField(
            model_name="pathfinderhikesubmission",
            name="submitter_present_for_playtest",
        ),
        migrations.AlterField(
            model_name="pathfinderhikesubmission",
            name="map_submitter_discord",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pathfinder_hike_submitters",
                to="discord.discordaccount",
                verbose_name="Map Submitter Discord",
            ),
        ),
        migrations.DeleteModel(
            name="PathfinderHikeAttendance",
        ),
        migrations.DeleteModel(
            name="PathfinderTestingLFGPost",
        ),
    ]
