# Generated by Django 4.1.1 on 2023-03-05 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("xbox_live", "0004_alter_xboxliveoauthtoken_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="xboxliveoauthtoken",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "OAuth Token",
                "verbose_name_plural": "OAuth Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="xboxliveusertoken",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Token",
                "verbose_name_plural": "User Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="xboxlivexststoken",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "XSTS Token",
                "verbose_name_plural": "XSTS Tokens",
            },
        ),
    ]
