# Generated by Django 4.1.1 on 2023-03-06 06:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trailblazer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trailblazertuesdayattendance",
            options={
                "ordering": ["-attendance_date"],
                "verbose_name": "Tuesday Attendance",
                "verbose_name_plural": "Tuesday Attendances",
            },
        ),
        migrations.AlterModelOptions(
            name="trailblazertuesdayreferral",
            options={
                "ordering": ["-referral_date"],
                "verbose_name": "Tuesday Referral",
                "verbose_name_plural": "Tuesday Referrals",
            },
        ),
        migrations.AlterModelOptions(
            name="trailblazervodreview",
            options={
                "ordering": ["-submission_date"],
                "verbose_name": "VOD Review",
                "verbose_name_plural": "VOD Reviews",
            },
        ),
    ]
