# Generated by Django 4.1.1 on 2023-06-02 17:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discord", "0001_initial"),
        ("trailblazer", "0002_alter_trailblazertuesdayattendance_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrailblazerVODReview",
            new_name="TrailblazerVODSubmission",
        ),
        migrations.AlterModelOptions(
            name="trailblazervodsubmission",
            options={
                "ordering": ["-submission_date"],
                "verbose_name": "VOD Submission",
                "verbose_name_plural": "VOD Submissions",
            },
        ),
        migrations.AlterModelTable(
            name="trailblazervodsubmission",
            table="TrailblazerVODSubmission",
        ),
    ]
