# Generated by Django 4.1.1 on 2023-06-02 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discord", "0001_initial"),
        (
            "trailblazer",
            "0003_rename_trailblazervodreview_trailblazervodsubmission_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TrailblazerExcellentVODReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("review_date", models.DateField(verbose_name="Review Date")),
                (
                    "review_message_link",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Review Message Link"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer_discord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="trailblazer_excellent_vod_reviewers",
                        to="discord.discordaccount",
                        verbose_name="Reviewer Discord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Excellent VOD Review",
                "verbose_name_plural": "Excellent VOD Reviews",
                "db_table": "TrailblazerExcellentVODReview",
                "ordering": ["-review_date"],
            },
        ),
    ]
