# Generated by Django 5.0.6 on 2024-06-08 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trailblazer", "0005_alter_trailblazerexcellentvodreview_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trailblazertuesdayreferral",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="trailblazertuesdayreferral",
            name="invitee_discord",
        ),
        migrations.RemoveField(
            model_name="trailblazertuesdayreferral",
            name="referrer_discord",
        ),
        migrations.RemoveField(
            model_name="trailblazervodsubmission",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="trailblazervodsubmission",
            name="submitter_discord",
        ),
        migrations.DeleteModel(
            name="TrailblazerExcellentVODReview",
        ),
        migrations.DeleteModel(
            name="TrailblazerTuesdayReferral",
        ),
        migrations.DeleteModel(
            name="TrailblazerVODSubmission",
        ),
    ]
