# Generated by Django 5.0.6 on 2024-05-16 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("discord", "0005_discordlfgchannelhelpprompt"),
        ("halo_infinite", "0005_alter_haloinfiniteplaylist_options_and_more"),
        ("xbox_live", "0005_alter_xboxliveoauthtoken_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MVT",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_at", models.DateTimeField()),
                ("mvt_points", models.IntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "earner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="mvt",
                        to="discord.discordaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "MVT",
                "verbose_name_plural": "MVTs",
                "db_table": "MVT",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamUpChallengeCompletion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "challenge",
                    models.CharField(
                        choices=[
                            ("BAIT_THE_FLAGS", "Bait the Flags"),
                            ("FIFTY_FISTS", "Fifty Fists"),
                            ("GRENADE_PARADE", "Grenade Parade"),
                            ("HUNDRED_HEADS", "Hundred Heads"),
                            ("MOST_VALUABLE_DRIVER", "Most Valuable Driver"),
                            ("OWN_THE_ZONES", "Own the Zones"),
                            ("SPEED_FOR_SEEDS", "Speed for Seeds"),
                            ("SPIN_CLASS", "Spin Class"),
                            ("STICKY_ICKY", "Sticky Icky"),
                            ("SUMMON_A_DEMON", "Summon a Demon"),
                        ]
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="halo_infinite.haloinfinitematch",
                    ),
                ),
                (
                    "xbox_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="xbox_live.xboxliveaccount",
                        verbose_name="Xbox Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge Completion",
                "verbose_name_plural": "Challenge Completions",
                "db_table": "TeamUpChallengeCompletion",
                "ordering": ["-created_at"],
            },
        ),
    ]
