# Generated by Django 5.0.6 on 2024-05-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("era_02", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamupchallengecompletion",
            name="xbox_account",
        ),
        migrations.AddField(
            model_name="teamupchallengecompletion",
            name="xuid",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Xbox Live ID"
            ),
            preserve_default=False,
        ),
    ]
