# Generated by Django 5.0.6 on 2024-05-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("era_02", "0002_remove_teamupchallengecompletion_xbox_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamupchallengecompletion",
            name="score",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teamupchallengecompletion",
            name="challenge",
            field=models.CharField(
                choices=[
                    ("BAIT_THE_FLAGS", "Bait the Flags"),
                    ("FORTY_FISTS", "Forty Fists"),
                    ("GRENADE_PARADE", "Grenade Parade"),
                    ("HUNDRED_HEADS", "Hundred Heads"),
                    ("MOST_VALUABLE_DRIVER", "Most Valuable Driver"),
                    ("OWN_THE_ZONES", "Own the Zones"),
                    ("SPEED_FOR_SEEDS", "Speed for Seeds"),
                    ("SPIN_CLASS", "Spin Class"),
                    ("STICKY_ICKY", "Sticky Icky"),
                    ("SUMMON_A_DEMON", "Summon a Demon"),
                ]
            ),
        ),
    ]
