# Generated by Django 4.1.1 on 2023-03-09 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discord", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunTimeFridayVoiceDisconnect",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(verbose_name="Disconnected At"),
                ),
                (
                    "channel_id",
                    models.CharField(max_length=20, verbose_name="Channel ID"),
                ),
                (
                    "channel_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Channel Name"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disconnector_discord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="disconnectors",
                        to="discord.discordaccount",
                        verbose_name="Disconnector Discord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Disconnect",
                "verbose_name_plural": "Voice Disconnects",
                "db_table": "FunTimeFridayVoiceDisconnect",
                "ordering": ["-disconnected_at"],
            },
        ),
        migrations.CreateModel(
            name="FunTimeFridayVoiceConnect",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("connected_at", models.DateTimeField(verbose_name="Connected At")),
                (
                    "channel_id",
                    models.CharField(max_length=20, verbose_name="Channel ID"),
                ),
                (
                    "channel_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Channel Name"
                    ),
                ),
                (
                    "connector_discord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="connectors",
                        to="discord.discordaccount",
                        verbose_name="Connector Discord",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Connect",
                "verbose_name_plural": "Voice Connects",
                "db_table": "FunTimeFridayVoiceConnect",
                "ordering": ["-connected_at"],
            },
        ),
    ]
