# Generated by Django 4.1.1 on 2023-06-19 21:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discord", "0003_alter_discordaccount_discord_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowcaseFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("map", "Map"),
                            ("mode", "Mode"),
                            ("prefab", "Prefab"),
                        ],
                        max_length=16,
                    ),
                ),
                ("file_id", models.UUIDField(verbose_name="File ID")),
                (
                    "position",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "showcase_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="showcase_owners",
                        to="discord.discordaccount",
                        verbose_name="Showcase Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Showcase File",
                "verbose_name_plural": "Showcase Files",
                "db_table": "ShowcaseFile",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShowcaseFileSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_id", models.UUIDField(verbose_name="Version ID")),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=512)),
                ("snapshot_date", models.DateField()),
                ("plays_recent", models.IntegerField()),
                ("plays_all_time", models.IntegerField()),
                ("favorites", models.IntegerField()),
                ("number_of_ratings", models.IntegerField()),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=15, max_digits=16),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="showcase.showcasefile",
                        verbose_name="Showcase File",
                    ),
                ),
            ],
            options={
                "verbose_name": "Showcase File Snapshot",
                "verbose_name_plural": "Showcase File Snapshots",
                "db_table": "ShowcaseFileSnapshot",
                "ordering": ["-snapshot_date"],
            },
        ),
    ]
