name: hft-backend (CD)
on:
  push:
    branches:
    - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy hft-backend
      runs-on: ubuntu-latest
      steps:
        - name: Code checkout
          uses: actions/checkout@v2
        - name: Set up Fly
          uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Deploy to Fly
          run: flyctl deploy --remote-only
