name: Continuous Deployment (CD)
on:
  push:
    branches:
    - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  checks:
    name: Run CI
    uses: HaloFunTime/hft-backend/.github/workflows/ci.yaml@main
  deploy:
      name: Deploy Production
      needs: checks
      runs-on: ubuntu-latest
      steps:
        - name: Code checkout
          uses: actions/checkout@v2
        - name: Set up Fly
          uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Deploy to Fly
          run: flyctl deploy --remote-only
