name: hft-backend (CI)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main
jobs:
  test:
    name: Test hft-backend
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v3
    - name: Check formatting
      uses: pre-commit/action@v3.0.0
    - name: Prepare .env File
      run: cp .env.example .env
    - name: Start containers
      run: docker-compose up -d
    - name: Run tests
      run: docker exec hftbackend python manage.py test apps
    - name: Stop containers
      if: always()
      run: docker-compose down
